spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/inter_bank?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: ibs
    password: password